/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.group5.Application;

import com.group5.Car.Car;
import com.group5.User.Customer;
import com.group5.User.User;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Josefe Gillego
 */
public class CarPanel extends javax.swing.JPanel {
    private JPanel parent;
    private Car car;
    private User user;
    private int id;
    EmployeePanel container;
    /**
     * Creates new form carPanel
     */
    public CarPanel(JPanel panel, Car car) {
        this.user = user;
        this.parent = parent;
        this.car = car;
        this.container = container;
        initComponents();
        //this.setBackground(new Color(0, 0, 0, 0));
        initializeCarDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LBLCarName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BTNViewCarDetails = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PNLAvailableColor = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(75, 84, 139));
        setPreferredSize(new java.awt.Dimension(180, 188));

        LBLCarName.setForeground(new java.awt.Color(242, 235, 235));
        LBLCarName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLCarName.setText("car name");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/!car.png"))); // NOI18N

        BTNViewCarDetails.setBackground(new java.awt.Color(109, 118, 173));
        BTNViewCarDetails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNViewCarDetails.setForeground(new java.awt.Color(242, 235, 235));
        BTNViewCarDetails.setText("View Car");
        BTNViewCarDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNViewCarDetailsActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Available");

        PNLAvailableColor.setBackground(new java.awt.Color(102, 255, 102));
        PNLAvailableColor.setPreferredSize(new java.awt.Dimension(16, 16));

        javax.swing.GroupLayout PNLAvailableColorLayout = new javax.swing.GroupLayout(PNLAvailableColor);
        PNLAvailableColor.setLayout(PNLAvailableColorLayout);
        PNLAvailableColorLayout.setHorizontalGroup(
            PNLAvailableColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        PNLAvailableColorLayout.setVerticalGroup(
            PNLAvailableColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLCarName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PNLAvailableColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(BTNViewCarDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLCarName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(PNLAvailableColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(BTNViewCarDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTNViewCarDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNViewCarDetailsActionPerformed
        
        CarViewPanel cvp = new CarViewPanel(container, car);
        cvp.setVisible(true);
        
    }//GEN-LAST:event_BTNViewCarDetailsActionPerformed

    private void initializeCarDetails(){
        this.LBLCarName.setText("ID:" + car.getCarID() + " " + car.getName());
        this.PNLAvailableColor.setBackground((car.getStatus().isRented())? Color.RED : Color.GREEN);
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNViewCarDetails;
    private javax.swing.JLabel LBLCarName;
    private javax.swing.JPanel PNLAvailableColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
