/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group5.Application;

import com.group5.Car.Car;
import com.group5.Car.Part;
import com.group5.Login.UserDBHandler;
import com.group5.User.User;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author Josefe Gillego
 */
public class CarViewPanel extends javax.swing.JFrame {
    
    private Car car;
    private String[] info;
    private UserDBHandler handler = UserDBHandler.getInstance();
    EmployeePanel container;
    public CarViewPanel(EmployeePanel container, Car car) {
        this.car = car;
        this.container = container;
        initComponents();
        getContentPane().setBackground(new java.awt.Color(29, 34, 67)); 
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        this.LBLName.setText(car.getName());
        
        String carInfo;
        carInfo =
                "License Plate: " + car.getLicensePlate()
                + "\n\nAvailable for Rent:" + Boolean.toString(!car.getStatus().isRented())
                + "\nRenter: " + ((car.getStatus().getOwner() != null)? car.getStatus().getOwner().getUsername() : "No Renter")
                + "\nRent Duration: " + car.getStatus().getRentDurationDays()
                + "\nRent Price per Day: " + ((car.getStatus().getPrice() != null)? car.getStatus().getPrice().getRentPricePerDay() : 0)
                + "\nTotal Calculated Price: " + ((car.getStatus().getPrice() != null)? car.getStatus().getPrice().calculatePrice(car.getStatus().getRentDurationDays()) : 0)
                + "\n\nBrand: " + car.getMake().getName()
                + "\nModel: " + car.getModel().getName()
                + "\nYear Manufactured: " + car.getModel().getModelYear()
                + "\nCountry of Origin: " + car.getMake().getCountry()
        ;
        
        carInfo +=
                "\n\nPiston Configuration: " + car.getParts().get(2).getSpecs()[0] +
                "\nMax Speed: " + car.getParts().get(2).getSpecs()[1] +
                "\nMax RPM: " + car.getParts().get(2).getSpecs()[2] +
                "\n0-100 KMH: " + car.getParts().get(2).getSpecs()[3] +
                "\nEngine Displacement: " + car.getParts().get(2).getSpecs()[4] +
                "\nPower: " + car.getParts().get(2).getSpecs()[5] +
                "\nTorque: " + car.getParts().get(2).getSpecs()[6] +
                "\nFuel Type: " + car.getParts().get(2).getSpecs()[7] +
                "\nCity Fuel Economy: " + car.getParts().get(2).getSpecs()[8] +
                "\nHighway Fuel Economy: " + car.getParts().get(2).getSpecs()[9]
        ;
        
        carInfo +=
                "\n\nBody Weight: " + car.getParts().get(0).getSpecs()[0] +
                "\nBody Length: " + car.getParts().get(0).getSpecs()[1] +
                "\nBody Width: " + car.getParts().get(0).getSpecs()[2] +
                "\nCargo Capacity: " + car.getParts().get(0).getSpecs()[3] +
                "\nTowing Capacity: " + car.getParts().get(0).getSpecs()[4] +
                "\nSeating Capacity: " + car.getParts().get(0).getSpecs()[5] +
                "\nFuel Capacity: " + car.getParts().get(0).getSpecs()[6] +
                "\nColor: " + car.getParts().get(0).getSpecs()[7] +
                "\nBody Type: " + car.getParts().get(0).getSpecs()[8]
        ;
        
        carInfo +=
                "\n\nWheel Drive Type: " + car.getParts().get(1).getSpecs()[0] +
                "\nTransmission Type: " + car.getParts().get(1).getSpecs()[1] +
                "\nGear Count: " + car.getParts().get(1).getSpecs()[2]
        ;



        
        this.TACarInfo.setText(carInfo);
        
        
        boolean condition = false;
        for(int carID : UserDBHandler.getLoggedInUser().getCarIDs()){
            if(carID == car.getCarID()){
                condition = true;
                break;
            }
        }
        if(condition == true){
            BTNRentCar.setText("RETURN CAR");
            
            
        }else{
            BTNRentCar.setText("RENT CAR");
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        popupMenu1 = new java.awt.PopupMenu();
        BTNRentCar = new javax.swing.JButton();
        CarIMG = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LBLName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TACarInfo = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(184, 38, 34));
        jLabel7.setText("Input car information to add to database records");

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNRentCar.setBackground(new java.awt.Color(148, 28, 0));
        BTNRentCar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNRentCar.setForeground(new java.awt.Color(242, 235, 235));
        BTNRentCar.setText("RENT CAR");
        BTNRentCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRentCarActionPerformed(evt);
            }
        });

        CarIMG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CarIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Misc/!car.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(223, 74, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 235, 235));
        jLabel2.setText("Car Info");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(54, 63, 125));

        LBLName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LBLName.setForeground(new java.awt.Color(242, 235, 235));
        LBLName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLName.setText("NAME");

        TACarInfo.setEditable(false);
        TACarInfo.setColumns(20);
        TACarInfo.setRows(5);
        jScrollPane1.setViewportView(TACarInfo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLName, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LBLName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CarIMG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNRentCar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNRentCar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNRentCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRentCarActionPerformed
        
        boolean condition = false;
        for(int carID : UserDBHandler.getLoggedInUser().getCarIDs()){
            if(carID == car.getCarID()){
                condition = true;
                break;
            }
        }
        if(condition == true){
            UserDBHandler.getLoggedInUser().removeCarID(car.getCarID());
            try {
                handler.updateUser(UserDBHandler.getLoggedInUser());
            } catch (IOException ex) {
                Logger.getLogger(CarViewPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }else{
            RentCarForm rcf = new RentCarForm(car);
            rcf.setVisible(true);
        }
        dispose();
        
        
    }//GEN-LAST:event_BTNRentCarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNRentCar;
    private javax.swing.JLabel CarIMG;
    private javax.swing.JLabel LBLName;
    private javax.swing.JTextArea TACarInfo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
