/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.group5.Application;

import com.group5.Car.Car;
import com.group5.Car.CarBuilder;
import com.group5.Car.CarDBHandler;
import com.group5.Car.Make;
import com.group5.Car.Model;
import com.group5.Car.Part;
import com.group5.Car.Parts.BodyFactory;
import com.group5.Car.Parts.DrivetrainFactory;
import com.group5.Car.Parts.EngineFactory;
import com.group5.Car.Price;
import com.group5.Car.RentStatus;
import java.awt.Component;
import java.io.IOException;

import javax.swing.JTextField;

/**
 *
 * @author norielloslos
 */
public class EditCarForm extends javax.swing.JFrame {
    
    /**
     * Creates new form AddCarForm
     */
    Car editingCar;
    String[] info;

    public EditCarForm(Car car) {

        initComponents();
        editingCar = car;
        getContentPane().setBackground(new java.awt.Color(29, 34, 67));
        
        String carInfo;
        carInfo =
            car.getCarID()
            + "," + car.getName()
            + "," + car.getMake().getName()
            + "," + car.getMake().getCountry()
            + "," + car.getModel().getName()
            + "," + car.getModel().getModelYear()
            + "," + car.getLicensePlate()
            + "," + Boolean.toString(car.getStatus().isRented())
            + "," + ((car.getStatus().getOwner() != null)? car.getStatus().getOwner().getUsername() : "Unowned")
            + "," + ((car.getStatus().getPrice() != null)? car.getStatus().getPrice().getRentPricePerDay() : 0)
            + "," + car.getStatus().getRentDurationDays()
        ;
        for (Part part : car.getParts()) {
            for (String spec : part.getSpecs()) {
                carInfo += "," + spec;
            }
        }
        info = carInfo.split(",");
        
        this.TFName.setText(info[1]);
        this.TFMakeName.setText(info[2]);
        this.TFMakeCountry.setText(info[3]);
        this.TFModelName.setText(info[4]);
        this.TFModelYear.setText(info[5]);
        this.TFPlate.setText(info[6]);
        this.TFBodyWeight.setText(info[11]);
        this.TFBodyLength.setText(info[12]);
        this.TFBodyWidth.setText(info[13]);
        this.TFBodyCargoCapacity.setText(info[14]);
        this.TFBodyTowingCapacity.setText(info[14]);
        this.TFBodySeatingCapacity.setText(info[16]);
        this.TFBodyFuelCapacity.setText(info[17]);
        this.TFBodyColor.setText(info[18]);
        this.TFBodyType.setText(info[19]);
        this.TFDrivetrainWheelDriveType.setText(info[20]);
        this.TFDrivetrainTransmissionType.setText(info[21]);
        this.TFDrivetrainGearCount.setText(info[22]);
        this.TFEnginePistonConfiguration.setText(info[23]);
        this.TFEngineMaxSpeed.setText(info[24]);
        this.TFEngineMaxRPM.setText(info[25]);
        this.TFEngineZeroToHundredKMH.setText(info[26]);
        this.TFEngineDisplacement.setText(info[27]);
        this.TFEnginePower.setText(info[28]);
        this.TFEngineTorque.setText(info[29]);
        this.TFEngineFuelType.setText(info[30]);
        this.TFEngineCityFuelEconomy.setText(info[31]);
        this.TFEngineHighwayFuelEconomy.setText(info[32]);
        this.TFPriceRentCostPerDay.setText(Double.toString(car.getStatus().getPrice().getRentPricePerDay()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PNLBasicInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TFMakeCountry = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TFModelName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TFName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TFModelYear = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        TFMakeName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TFBodyWeight = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TFBodyWidth = new javax.swing.JTextField();
        TFBodyLength = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TFBodyCargoCapacity = new javax.swing.JTextField();
        TFBodyFuelCapacity = new javax.swing.JTextField();
        TFBodyTowingCapacity = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TFBodySeatingCapacity = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        TFBodyColor = new javax.swing.JTextField();
        TFBodyType = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        TFDrivetrainWheelDriveType = new javax.swing.JTextField();
        TFDrivetrainTransmissionType = new javax.swing.JTextField();
        TFDrivetrainGearCount = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        TFPlate = new javax.swing.JTextField();
        PNLEngineInfo = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        TFEnginePistonConfiguration = new javax.swing.JTextField();
        TFEngineMaxSpeed = new javax.swing.JTextField();
        TFEngineMaxRPM = new javax.swing.JTextField();
        TFEngineZeroToHundredKMH = new javax.swing.JTextField();
        TFEngineDisplacement = new javax.swing.JTextField();
        TFEnginePower = new javax.swing.JTextField();
        TFEngineTorque = new javax.swing.JTextField();
        TFEngineFuelType = new javax.swing.JTextField();
        TFEngineCityFuelEconomy = new javax.swing.JTextField();
        TFEngineHighwayFuelEconomy = new javax.swing.JTextField();
        BTTClear = new javax.swing.JButton();
        BTTSave = new javax.swing.JButton();
        PNLPrice = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        TFPriceRentCostPerDay = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jSeparator2.setForeground(new java.awt.Color(242, 235, 235));

        jSeparator3.setForeground(new java.awt.Color(242, 235, 235));

        setBackground(new java.awt.Color(75, 84, 139));

        jPanel3.setBackground(new java.awt.Color(223, 74, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 235, 235));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EDIT CAR");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(184, 38, 34));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Edit car records in the database");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(24, 24, 24))
        );

        PNLBasicInfo.setBackground(new java.awt.Color(54, 63, 125));
        PNLBasicInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 235, 235));
        jLabel1.setText("Name:");

        TFMakeCountry.setBackground(new java.awt.Color(109, 118, 173));
        TFMakeCountry.setForeground(new java.awt.Color(242, 235, 235));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 235, 235));
        jLabel3.setText("Brand:");

        TFModelName.setBackground(new java.awt.Color(109, 118, 173));
        TFModelName.setForeground(new java.awt.Color(242, 235, 235));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 235, 235));
        jLabel4.setText("Country:");

        TFName.setBackground(new java.awt.Color(109, 118, 173));
        TFName.setForeground(new java.awt.Color(242, 235, 235));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 235, 235));
        jLabel5.setText("Year:");

        TFModelYear.setBackground(new java.awt.Color(109, 118, 173));
        TFModelYear.setForeground(new java.awt.Color(242, 235, 235));

        jSeparator1.setForeground(new java.awt.Color(242, 235, 235));

        TFMakeName.setBackground(new java.awt.Color(109, 118, 173));
        TFMakeName.setForeground(new java.awt.Color(242, 235, 235));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 235, 235));
        jLabel6.setText("Model:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 235, 235));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Basic Info");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 235, 235));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Car Body Info");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(242, 235, 235));
        jLabel10.setText("Weight(kg):");

        TFBodyWeight.setBackground(new java.awt.Color(109, 118, 173));
        TFBodyWeight.setForeground(new java.awt.Color(242, 235, 235));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(242, 235, 235));
        jLabel11.setText("Length(m):");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(242, 235, 235));
        jLabel12.setText("Width(m):");

        TFBodyWidth.setBackground(new java.awt.Color(109, 118, 173));
        TFBodyWidth.setForeground(new java.awt.Color(242, 235, 235));

        TFBodyLength.setBackground(new java.awt.Color(109, 118, 173));
        TFBodyLength.setForeground(new java.awt.Color(242, 235, 235));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(242, 235, 235));
        jLabel13.setText("Seating Capacity: ");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(242, 235, 235));
        jLabel14.setText("Cargo Capacity(kg):");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(242, 235, 235));
        jLabel15.setText("Towing Capacity(kg):");

        TFBodyCargoCapacity.setBackground(new java.awt.Color(109, 118, 173));
        TFBodyCargoCapacity.setForeground(new java.awt.Color(242, 235, 235));

        TFBodyFuelCapacity.setEditable(false);
        TFBodyFuelCapacity.setBackground(new java.awt.Color(109, 118, 173));
        TFBodyFuelCapacity.setForeground(new java.awt.Color(242, 235, 235));

        TFBodyTowingCapacity.setBackground(new java.awt.Color(109, 118, 173));
        TFBodyTowingCapacity.setForeground(new java.awt.Color(242, 235, 235));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(242, 235, 235));
        jLabel16.setText("Fuel Capacity(li/kwh):");

        TFBodySeatingCapacity.setBackground(new java.awt.Color(109, 118, 173));
        TFBodySeatingCapacity.setForeground(new java.awt.Color(242, 235, 235));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(242, 235, 235));
        jLabel17.setText("Body Color:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(242, 235, 235));
        jLabel18.setText("Body Type");

        TFBodyColor.setBackground(new java.awt.Color(109, 118, 173));
        TFBodyColor.setForeground(new java.awt.Color(242, 235, 235));

        TFBodyType.setBackground(new java.awt.Color(109, 118, 173));
        TFBodyType.setForeground(new java.awt.Color(242, 235, 235));

        jSeparator4.setForeground(new java.awt.Color(242, 235, 235));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(242, 235, 235));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Car Drivetrain Info");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(242, 235, 235));
        jLabel20.setText("Wheel Drive Type:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(242, 235, 235));
        jLabel21.setText("Transmission Type:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(242, 235, 235));
        jLabel22.setText("Gear Count:");

        TFDrivetrainWheelDriveType.setBackground(new java.awt.Color(109, 118, 173));
        TFDrivetrainWheelDriveType.setForeground(new java.awt.Color(242, 235, 235));

        TFDrivetrainTransmissionType.setBackground(new java.awt.Color(109, 118, 173));
        TFDrivetrainTransmissionType.setForeground(new java.awt.Color(242, 235, 235));

        TFDrivetrainGearCount.setBackground(new java.awt.Color(109, 118, 173));
        TFDrivetrainGearCount.setForeground(new java.awt.Color(242, 235, 235));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(242, 235, 235));
        jLabel29.setText("Plate#:");

        TFPlate.setBackground(new java.awt.Color(109, 118, 173));
        TFPlate.setForeground(new java.awt.Color(242, 235, 235));

        javax.swing.GroupLayout PNLBasicInfoLayout = new javax.swing.GroupLayout(PNLBasicInfo);
        PNLBasicInfo.setLayout(PNLBasicInfoLayout);
        PNLBasicInfoLayout.setHorizontalGroup(
            PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLBasicInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PNLBasicInfoLayout.createSequentialGroup()
                        .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFBodyCargoCapacity)
                            .addComponent(TFBodyFuelCapacity)
                            .addComponent(TFBodyTowingCapacity)
                            .addComponent(TFBodySeatingCapacity, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(PNLBasicInfoLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFBodyWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFBodyLength, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFBodyWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PNLBasicInfoLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFBodyColor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFBodyType, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator4)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PNLBasicInfoLayout.createSequentialGroup()
                        .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFDrivetrainWheelDriveType)
                            .addComponent(TFDrivetrainGearCount)
                            .addComponent(TFDrivetrainTransmissionType)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLBasicInfoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TFMakeName, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(TFName)
                            .addComponent(TFMakeCountry))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFModelName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFModelYear, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PNLBasicInfoLayout.setVerticalGroup(
            PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLBasicInfoLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFMakeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFModelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFMakeCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFModelYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFBodyWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFBodyLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFBodyWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFBodyCargoCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFBodyTowingCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFBodyFuelCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFBodySeatingCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFBodyColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFBodyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFDrivetrainWheelDriveType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFDrivetrainTransmissionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLBasicInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFDrivetrainGearCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PNLEngineInfo.setBackground(new java.awt.Color(54, 63, 125));
        PNLEngineInfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(242, 235, 235));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Car Engine Info");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(242, 235, 235));
        jLabel30.setText("Max. Speed(kmh):");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(242, 235, 235));
        jLabel31.setText("Max. RPM:");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(242, 235, 235));
        jLabel32.setText("0-100km\\h(sec):");

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(242, 235, 235));
        jLabel33.setText("Engine Displacement(li):");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(242, 235, 235));
        jLabel34.setText("Power(Ps):");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(242, 235, 235));
        jLabel35.setText("Torque(Nm):");

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(242, 235, 235));
        jLabel36.setText("Fuel Type:");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(242, 235, 235));
        jLabel38.setText("City Fuel Econ. (km/g):");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(242, 235, 235));
        jLabel39.setText("Highway Fuel Econ. (km/g):");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(242, 235, 235));
        jLabel40.setText("Piston Configuration:");

        TFEnginePistonConfiguration.setBackground(new java.awt.Color(109, 118, 173));
        TFEnginePistonConfiguration.setForeground(new java.awt.Color(242, 235, 235));

        TFEngineMaxSpeed.setBackground(new java.awt.Color(109, 118, 173));
        TFEngineMaxSpeed.setForeground(new java.awt.Color(242, 235, 235));

        TFEngineMaxRPM.setBackground(new java.awt.Color(109, 118, 173));
        TFEngineMaxRPM.setForeground(new java.awt.Color(242, 235, 235));

        TFEngineZeroToHundredKMH.setBackground(new java.awt.Color(109, 118, 173));
        TFEngineZeroToHundredKMH.setForeground(new java.awt.Color(242, 235, 235));

        TFEngineDisplacement.setBackground(new java.awt.Color(109, 118, 173));
        TFEngineDisplacement.setForeground(new java.awt.Color(242, 235, 235));

        TFEnginePower.setBackground(new java.awt.Color(109, 118, 173));
        TFEnginePower.setForeground(new java.awt.Color(242, 235, 235));

        TFEngineTorque.setBackground(new java.awt.Color(109, 118, 173));
        TFEngineTorque.setForeground(new java.awt.Color(242, 235, 235));

        TFEngineFuelType.setBackground(new java.awt.Color(109, 118, 173));
        TFEngineFuelType.setForeground(new java.awt.Color(242, 235, 235));

        TFEngineCityFuelEconomy.setBackground(new java.awt.Color(109, 118, 173));
        TFEngineCityFuelEconomy.setForeground(new java.awt.Color(242, 235, 235));

        TFEngineHighwayFuelEconomy.setBackground(new java.awt.Color(109, 118, 173));
        TFEngineHighwayFuelEconomy.setForeground(new java.awt.Color(242, 235, 235));

        javax.swing.GroupLayout PNLEngineInfoLayout = new javax.swing.GroupLayout(PNLEngineInfo);
        PNLEngineInfo.setLayout(PNLEngineInfoLayout);
        PNLEngineInfoLayout.setHorizontalGroup(
            PNLEngineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLEngineInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLEngineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNLEngineInfoLayout.createSequentialGroup()
                        .addGroup(PNLEngineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PNLEngineInfoLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(PNLEngineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel39))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PNLEngineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFEnginePistonConfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFEngineMaxSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFEngineMaxRPM, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFEngineZeroToHundredKMH, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFEngineDisplacement, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFEnginePower, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFEngineTorque, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFEngineFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFEngineCityFuelEconomy, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFEngineHighwayFuelEconomy, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PNLEngineInfoLayout.setVerticalGroup(
            PNLEngineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLEngineInfoLayout.createSequentialGroup()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLEngineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFEnginePistonConfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLEngineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFEngineMaxSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLEngineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFEngineMaxRPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLEngineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFEngineZeroToHundredKMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLEngineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFEngineDisplacement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLEngineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFEnginePower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLEngineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFEngineTorque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLEngineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFEngineFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLEngineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFEngineCityFuelEconomy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLEngineInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFEngineHighwayFuelEconomy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        BTTClear.setBackground(new java.awt.Color(148, 28, 0));
        BTTClear.setFont(new java.awt.Font("Brandon Text", 1, 24)); // NOI18N
        BTTClear.setForeground(new java.awt.Color(242, 235, 235));
        BTTClear.setText("RESET");
        BTTClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTTClearActionPerformed(evt);
            }
        });

        BTTSave.setBackground(new java.awt.Color(148, 28, 0));
        BTTSave.setFont(new java.awt.Font("Brandon Text", 1, 24)); // NOI18N
        BTTSave.setForeground(new java.awt.Color(242, 235, 235));
        BTTSave.setText("SAVE");
        BTTSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTTSaveActionPerformed(evt);
            }
        });

        PNLPrice.setBackground(new java.awt.Color(54, 63, 125));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(242, 235, 235));
        jLabel41.setText("Rent Cost/Day(Php):");

        TFPriceRentCostPerDay.setBackground(new java.awt.Color(109, 118, 173));
        TFPriceRentCostPerDay.setForeground(new java.awt.Color(242, 235, 235));

        javax.swing.GroupLayout PNLPriceLayout = new javax.swing.GroupLayout(PNLPrice);
        PNLPrice.setLayout(PNLPriceLayout);
        PNLPriceLayout.setHorizontalGroup(
            PNLPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLPriceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFPriceRentCostPerDay)
                .addContainerGap())
        );
        PNLPriceLayout.setVerticalGroup(
            PNLPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLPriceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PNLPriceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFPriceRentCostPerDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PNLBasicInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PNLEngineInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTTClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTTSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PNLPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PNLEngineInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PNLPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTTSave, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTTClear, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PNLBasicInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void BTTClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTTClearActionPerformed
        this.TFName.setText(info[1]);
        this.TFMakeName.setText(info[2]);
        this.TFMakeCountry.setText(info[3]);
        this.TFModelName.setText(info[4]);
        this.TFModelYear.setText(info[5]);
        this.TFPlate.setText(info[6]);
        this.TFBodyWeight.setText(info[11]);
        this.TFBodyLength.setText(info[12]);
        this.TFBodyWidth.setText(info[13]);
        this.TFBodyCargoCapacity.setText(info[14]);
        this.TFBodyTowingCapacity.setText(info[14]);
        this.TFBodySeatingCapacity.setText(info[16]);
        this.TFBodyFuelCapacity.setText(info[17]);
        this.TFBodyColor.setText(info[18]);
        this.TFBodyType.setText(info[19]);
        this.TFDrivetrainWheelDriveType.setText(info[20]);
        this.TFDrivetrainTransmissionType.setText(info[21]);
        this.TFDrivetrainGearCount.setText(info[22]);
        this.TFEnginePistonConfiguration.setText(info[23]);
        this.TFEngineMaxSpeed.setText(info[24]);
        this.TFEngineMaxRPM.setText(info[25]);
        this.TFEngineZeroToHundredKMH.setText(info[26]);
        this.TFEngineDisplacement.setText(info[27]);
        this.TFEnginePower.setText(info[28]);
        this.TFEngineTorque.setText(info[29]);
        this.TFEngineFuelType.setText(info[30]);
        this.TFEngineCityFuelEconomy.setText(info[31]);
        this.TFEngineHighwayFuelEconomy.setText(info[32]);
    }//GEN-LAST:event_BTTClearActionPerformed

    private void BTTSaveActionPerformed(java.awt.event.ActionEvent evt) {                                        
        
        Make make = new Make(this.TFMakeName.getText(), this.TFMakeCountry.getText());
        
        CarBuilder carbuilder = new CarBuilder();
        carbuilder
            .setName(this.TFName.getText())
            .setMake(make)
            .setModel(new Model(this.TFModelName.getText(), make, Integer.parseInt(this.TFModelYear.getText())))
            .setPlate(this.TFPlate.getText())
            .setStatus(new RentStatus(new Price(Double.parseDouble(this.TFPriceRentCostPerDay.getText()))))
            .addPart(new BodyFactory().create()
                .setBodyWeight(Double.parseDouble(this.TFBodyWeight.getText()))
                .setBodyLength(Double.parseDouble(this.TFBodyLength.getText()))
                    .setBodyWidth(Double.parseDouble(this.TFBodyWidth.getText()))
                    .setCargoCapacity(Double.parseDouble(this.TFBodyCargoCapacity.getText()))
                    .setTowingCapacity(Double.parseDouble(this.TFBodyTowingCapacity.getText()))
                    .setSeatingCapacity(Integer.parseInt(this.TFBodySeatingCapacity.getText()))
                    .setFuelCapacity(Double.parseDouble(this.TFBodyFuelCapacity.getText()))
                    .setColor(this.TFBodyColor.getText())
                    .setBodyType(this.TFBodyType.getText())
            ).addPart(new DrivetrainFactory().create()
                .setWheelDriveType(this.TFDrivetrainWheelDriveType.getText())
                    .setTransmissionType(this.TFDrivetrainTransmissionType.getText())
                    .setGearCount(Integer.parseInt(this.TFDrivetrainGearCount.getText()))
            ).addPart(new EngineFactory().create()
                    .setPistonConfiguration(this.TFEnginePistonConfiguration.getText())
                    .setMaxSpeed(Double.parseDouble(this.TFEngineMaxSpeed.getText()))
                    .setMaxRPM(Double.parseDouble(this.TFEngineMaxRPM.getText()))
                    .setZeroToHundredKMH(Double.parseDouble(this.TFEngineZeroToHundredKMH.getText()))
                    .setEngineDisplacement(Double.parseDouble(this.TFEngineDisplacement.getText()))
                    .setPower(Integer.parseInt(this.TFEnginePower.getText()))
                    .setTorque(Integer.parseInt(this.TFEngineTorque.getText()))
                    .setFuelType(this.TFEngineFuelType.getText())
                    .setCityFuelEconomy(Double.parseDouble(this.TFEngineCityFuelEconomy.getText()))
                    .setHighwayFuelEconomy(Double.parseDouble(this.TFEngineHighwayFuelEconomy.getText()))
            )
        ;

        try {
            CarDBHandler.editCar(editingCar.getCarID(), carbuilder.build());
        } catch (IOException e) {
            e.printStackTrace();
        }
                
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTTClear;
    private javax.swing.JButton BTTSave;
    private javax.swing.JPanel PNLBasicInfo;
    private javax.swing.JPanel PNLEngineInfo;
    private javax.swing.JPanel PNLPrice;
    private javax.swing.JTextField TFBodyCargoCapacity;
    private javax.swing.JTextField TFBodyColor;
    private javax.swing.JTextField TFBodyFuelCapacity;
    private javax.swing.JTextField TFBodyLength;
    private javax.swing.JTextField TFBodySeatingCapacity;
    private javax.swing.JTextField TFBodyTowingCapacity;
    private javax.swing.JTextField TFBodyType;
    private javax.swing.JTextField TFBodyWeight;
    private javax.swing.JTextField TFBodyWidth;
    private javax.swing.JTextField TFDrivetrainGearCount;
    private javax.swing.JTextField TFDrivetrainTransmissionType;
    private javax.swing.JTextField TFDrivetrainWheelDriveType;
    private javax.swing.JTextField TFEngineCityFuelEconomy;
    private javax.swing.JTextField TFEngineDisplacement;
    private javax.swing.JTextField TFEngineFuelType;
    private javax.swing.JTextField TFEngineHighwayFuelEconomy;
    private javax.swing.JTextField TFEngineMaxRPM;
    private javax.swing.JTextField TFEngineMaxSpeed;
    private javax.swing.JTextField TFEnginePistonConfiguration;
    private javax.swing.JTextField TFEnginePower;
    private javax.swing.JTextField TFEngineTorque;
    private javax.swing.JTextField TFEngineZeroToHundredKMH;
    private javax.swing.JTextField TFMakeCountry;
    private javax.swing.JTextField TFMakeName;
    private javax.swing.JTextField TFModelName;
    private javax.swing.JTextField TFModelYear;
    private javax.swing.JTextField TFName;
    private javax.swing.JTextField TFPlate;
    private javax.swing.JTextField TFPriceRentCostPerDay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
